apiVersion: v1
kind: Pod
metadata:
  name: nginx-burstable
spec:
  containers:
  - image: nginx
    name: nginx-burstable
    resources:
      limits:
        memory: "100Mi"
        cpu: "200m"
      requests:
        memory: "50Mi"
        cpu: "100m"
